### PR TITLE
add a method to force a prebuild

### PR DESCRIPTION
**Pull request by mathiask88**
This PR adds a method to force a prebuild without a version bump. I don't want to release a new version of my addon just to add some node v9 prebuilds :) Now `prebuild-ci` checks the latest commit description for `FORCE_PREBUILD`.

### CODE REVIEW

**Comment by juliangruber** [comment]
what about going to your ci environment and triggering a rebuild? that's what i always do

**Comment by juliangruber** [comment]
ah i see, you want to land new commits to an old release basically. that gets tricky, if your code changes you should make a new release.

**Comment by mathiask88** [comment]
My code does not change that much, and now is a point where I want to add node v9 to CIs and just add these prebuilds to the old release. Maybe there is an option that I missed.

**Comment by juliangruber** [comment]
Ok, I'm +-0. There can be some edge cases to this, but I also see that making a new release just for adding a new platform to your travis.yml is overhead.

Can another maintainer comment, please?

**Comment by vweevers** [comment]
Another option is to temporarily add `git checkout <old version tag>` to your `.travis.yml` (or other CI).

**Comment by vweevers** [comment]
> Whats the point of checking out an older version in travis?

The workflow is as follows. Add node 9 and a `git checkout` command to `.travis.yml`:

```yaml
- node_js:
  - "9"
  - "8"
- install:
  - git checkout <old version tag>
```

Then commit and push this, which triggers a Travis build. You may need a different build step (maybe `before_install`) and/or disable shallow cloning to actually make it work. But the idea is, that the travis job uses a new build matrix (with node 9), to build an older version of your native module. And because we checked out a tagged commit, `prebuild-ci` will upload a prebuild for node 9.

**Comment by mathiask88** [comment]
@vweevers I didn't know that `prebuild-ci` builds on tagged releases? It just checks the package version and this is the same for the new build environment and the tagged release.

**Comment by vweevers** [comment]
@mathiask88 ah yes you're right. The effect is the same though, because it'll be in a detached head state, where `HEAD` refers to the tagged commit, and `HEAD~1` one commit before that.

**Comment by juliangruber** [comment]
Closing this for lack of interest and resolution

**Pull request closed without merging**
