### PR TITLE
Version changed

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by vweevers** [comment]
Why do we have a `package-lock` here?

**Comment by ralphtheninja** [comment]
> Why do we have a `package-lock` here?

I'm guessing because it's a pure cli tool, so an "application".

**Comment by vweevers** [comment]
> On the other hand it's used as a devDependency

And in that case, npm ignores the lock file anyway. I suggest removing it. WDYT?

**Comment by ralphtheninja** [comment]
> And in that case, npm ignores the lock file anyway. I suggest removing it. WDYT?

I don't mind. It's always possible to put it back if someone complains. Should we make a new major for this reason?

**Pull request merged**
